# Generated by Django 4.1.5 on 2023-02-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('calleYNumero', models.TextField(max_length=100)),
                ('colonia', models.CharField(max_length=60)),
                ('municipio', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=60)),
                ('pais', models.CharField(max_length=60)),
                ('cp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=600)),
                ('departamento', models.CharField(max_length=60)),
                ('talla', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=60)),
                ('tipo', models.CharField(max_length=60)),
                ('existencia', models.IntegerField()),
            ],
        ),
    ]
