# Generated by Django 4.1.5 on 2023-02-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAbrigate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('iva', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
