# Generated by Django 4.1.5 on 2023-02-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAbrigate', '0002_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(height_field=100, null=True, upload_to='', width_field=100),
        ),
    ]
